type: picture-elements
image: local/kitchenNoLight.png
elements:
  - type: image
    title: timeofday
    entity: sensor.timeofday
    style:
      left: 50%
      top: 50%
      width: 100%
    state_image:
      day: /local/kitchenNoLight.png
      night: /local/kitchenNoLight.png
  - type: state-badge
    title: humidity
    entity: sensor.humidity_1
    style:
      top: 28%
      left: 44%
  - type: state-badge
    entity: sensor.temperature_2
    title: temperature
    style:
      top: 80%
      left: 55%